# -*- coding: utf-8 -*-
"""Urban_change_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1To7C_kFtWmQtKc8JJRNFX20QLttihEKn
"""



"""
Urban Change Detection – Encroachment Monitoring

This project classifies aerial images into:
- Vegetation
- Water
- Roads
- Buildings

It calculates percentage area of each land cover class.
"""

import cv2
import numpy as np
import os
import matplotlib.pyplot as plt



image_folder = "images"
output_folder = "output_images"

os.makedirs(output_folder, exist_ok=True)

image_files = [f for f in os.listdir(image_folder) if f.endswith(('.jpg', '.png', '.jpeg'))]




for filename in image_files:

    print(f"\nProcessing: {filename}")

    image_path = os.path.join(image_folder, filename)
    image = cv2.imread(image_path)

    if image is None:
        print("Error loading image:", filename)
        continue

    image = cv2.resize(image, (800, 600))


    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)


    lower_green = np.array([35, 40, 40])
    upper_green = np.array([85, 255, 255])


    lower_blue = np.array([90, 50, 50])
    upper_blue = np.array([130, 255, 255])


    lower_road = np.array([0, 0, 50])
    upper_road = np.array([180, 50, 200])


    lower_building = np.array([0, 0, 200])
    upper_building = np.array([180, 60, 255])



    mask_green = cv2.inRange(hsv, lower_green, upper_green)
    mask_blue = cv2.inRange(hsv, lower_blue, upper_blue)
    mask_road = cv2.inRange(hsv, lower_road, upper_road)
    mask_building = cv2.inRange(hsv, lower_building, upper_building)

    kernel = np.ones((5, 5), np.uint8)

    mask_green = cv2.morphologyEx(mask_green, cv2.MORPH_CLOSE, kernel)
    mask_blue = cv2.morphologyEx(mask_blue, cv2.MORPH_CLOSE, kernel)
    mask_road = cv2.morphologyEx(mask_road, cv2.MORPH_CLOSE, kernel)
    mask_building = cv2.morphologyEx(mask_building, cv2.MORPH_CLOSE, kernel)



    segmented = image.copy()

    contours_green, _ = cv2.findContours(mask_green, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contours_blue, _ = cv2.findContours(mask_blue, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contours_road, _ = cv2.findContours(mask_road, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contours_building, _ = cv2.findContours(mask_building, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    cv2.drawContours(segmented, contours_green, -1, (0, 255, 0), 2)
    cv2.drawContours(segmented, contours_blue, -1, (255, 0, 0), 2)
    cv2.drawContours(segmented, contours_road, -1, (0, 0, 255), 2)
    cv2.drawContours(segmented, contours_building, -1, (0, 255, 255), 2)


    total_pixels = image.shape[0] * image.shape[1]

    green_pixels = cv2.countNonZero(mask_green)
    blue_pixels = cv2.countNonZero(mask_blue)
    road_pixels = cv2.countNonZero(mask_road)
    building_pixels = cv2.countNonZero(mask_building)

    veg_percent = round((green_pixels / total_pixels) * 100, 2)
    water_percent = round((blue_pixels / total_pixels) * 100, 2)
    road_percent = round((road_pixels / total_pixels) * 100, 2)
    building_percent = round((building_pixels / total_pixels) * 100, 2)

    print("Vegetation %:", veg_percent)
    print("Water %:", water_percent)
    print("Road %:", road_percent)
    print("Building %:", building_percent)



    plt.figure(figsize=(10, 6))
    plt.imshow(cv2.cvtColor(segmented, cv2.COLOR_BGR2RGB))
    plt.title(f"Segmented Output - {filename}")
    plt.axis("off")
    plt.show()



    save_path = os.path.join(output_folder, "segmented_" + filename)
    cv2.imwrite(save_path, segmented)


print("\nAll images processed successfully!")

